testing the bitwarden via node setup

diff --git a/installers/bitwarden-cli.install b/installers/bitwarden-cli.install
--- a/installers/bitwarden-cli.install
+++ b/installers/bitwarden-cli.install
@@ -2,4 +2,12 @@
 # shellcheck disable=SC1090
 source "$(dirname "$(readlink -e -- "$0")")/core.source"
 
-sudo snap install bw
+if which snap > /dev/null; then
+  sudo snap install bw
+elif which node > /dev/null; then
+  sudo npm install -g @bitwarden/cli
+else
+  >&2 echo ":: unable to install bitwarden cli"
+  exit 1
+fi
+
